config/routes.rb
Rails.application.routes.draw do

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  resources :mtopics do
    resources :mposts, except: [:index], controller: 'mtopics/mposts'
  end

  resources :mposts, only: [:index] do
    resources :mcomments, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  devise_for :users
  resources :users, only: [:update, :show, :index]
  resources :events
  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

default_scope { order('created_at DESC') }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  	@events = Event.all
      authorize @events
  end

  def show
  	@event = Event.find(params[:id])
  end

  def new
    @event = Event.new
      authorize @event
  end

  def create
    @event = Event.new(params.require(:event).permit(:title, :body))
      authorize @event
    if @event.save
      flash[:notice] = "Event was saved."
      redirect_to @event
    else
      flash[:error] = "There was an error saving the event. Please try again."
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
      authorize @event
  end

  def update
    @event = Event.find(params[:id])
      authorize @event
    if @event.update_attributes(params.require(:event).permit(:title, :body))
      flash[:notice] = "Event was updated."
      redirect_to @event
    else
      flash[:error] = "There was an error saving the event. Please try again."
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    title = @event.title

    authorize @event
    if @event.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to events_path
    else
      flash[:error] = "There was an error deleting the event."
      render :show
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit Events</h1>
 
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for events</p>
    <ul>
      <li>Make sure the it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @event do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter event title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter event body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<h1>Events</h1>
<% if policy(Event.new).create? %>
<%= link_to "New Event", new_event_path, class: 'btn btn-success' %>
<% end %>
<% @events.each do |event| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
       <%= link_to event.title, event %>
      </h4>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>
 
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for events</p>
    <ul>
      <li>Must be fun</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @event do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter event title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter event body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<div class="row">
  <div class="col-md-8">
   <p><%= markdown @event.body %></p>
  </div>
  <div class="col-md-4">
    <% if policy(@event).edit? %>
      <%= link_to "Edit", edit_event_path(@event), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@event).destroy? %>
      <%= link_to "Delete Event", @event, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this event?' } %> 
      <% end %>
  </div>
</div>